%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  }
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx
mov rsp, 0xe8000000

; bit 0: adc ecx-width, V=0x7FFFFFFF, stc  (dst==src two-op form)
mov ecx, 0x7FFFFFFF
mov esi, 0x7FFFFFFF
stc
adc ecx, esi
pushfq
pop r8
mov eax, 0x7FFFFFFF
stc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: adc ecx-width, V=0x7FFFFFFF, clc  (dst==src two-op form)
mov ecx, 0x7FFFFFFF
mov esi, 0x7FFFFFFF
clc
adc ecx, esi
pushfq
pop r8
mov eax, 0x7FFFFFFF
clc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: adc ecx-width, V=0x80000000, stc  (dst==src two-op form)
mov ecx, 0x80000000
mov esi, 0x80000000
stc
adc ecx, esi
pushfq
pop r8
mov eax, 0x80000000
stc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: adc ecx-width, V=0x80000000, clc  (dst==src two-op form)
mov ecx, 0x80000000
mov esi, 0x80000000
clc
adc ecx, esi
pushfq
pop r8
mov eax, 0x80000000
clc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: adc ecx-width, V=0x40000000, stc  (dst==src two-op form)
mov ecx, 0x40000000
mov esi, 0x40000000
stc
adc ecx, esi
pushfq
pop r8
mov eax, 0x40000000
stc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: adc ecx-width, V=0x40000000, clc  (dst==src two-op form)
mov ecx, 0x40000000
mov esi, 0x40000000
clc
adc ecx, esi
pushfq
pop r8
mov eax, 0x40000000
clc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: adc ecx-width, V=0xFFFFFFFF, stc  (dst==src two-op form)
mov ecx, 0xFFFFFFFF
mov esi, 0xFFFFFFFF
stc
adc ecx, esi
pushfq
pop r8
mov eax, 0xFFFFFFFF
stc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: adc ecx-width, V=0xFFFFFFFF, clc  (dst==src two-op form)
mov ecx, 0xFFFFFFFF
mov esi, 0xFFFFFFFF
clc
adc ecx, esi
pushfq
pop r8
mov eax, 0xFFFFFFFF
clc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: adc ecx-width, V=0x12345678, stc  (dst==src two-op form)
mov ecx, 0x12345678
mov esi, 0x12345678
stc
adc ecx, esi
pushfq
pop r8
mov eax, 0x12345678
stc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: adc ecx-width, V=0x12345678, clc  (dst==src two-op form)
mov ecx, 0x12345678
mov esi, 0x12345678
clc
adc ecx, esi
pushfq
pop r8
mov eax, 0x12345678
clc
adc eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: sbb ecx-width, V=0x7FFFFFFF, stc  (dst==src two-op form)
mov ecx, 0x7FFFFFFF
mov esi, 0x7FFFFFFF
stc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x7FFFFFFF
stc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: sbb ecx-width, V=0x7FFFFFFF, clc  (dst==src two-op form)
mov ecx, 0x7FFFFFFF
mov esi, 0x7FFFFFFF
clc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x7FFFFFFF
clc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: sbb ecx-width, V=0x80000000, stc  (dst==src two-op form)
mov ecx, 0x80000000
mov esi, 0x80000000
stc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x80000000
stc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: sbb ecx-width, V=0x80000000, clc  (dst==src two-op form)
mov ecx, 0x80000000
mov esi, 0x80000000
clc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x80000000
clc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: sbb ecx-width, V=0x40000000, stc  (dst==src two-op form)
mov ecx, 0x40000000
mov esi, 0x40000000
stc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x40000000
stc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: sbb ecx-width, V=0x40000000, clc  (dst==src two-op form)
mov ecx, 0x40000000
mov esi, 0x40000000
clc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x40000000
clc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 15
or rbx, rax

; bit 16: sbb ecx-width, V=0xFFFFFFFF, stc  (dst==src two-op form)
mov ecx, 0xFFFFFFFF
mov esi, 0xFFFFFFFF
stc
sbb ecx, esi
pushfq
pop r8
mov eax, 0xFFFFFFFF
stc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 16
or rbx, rax

; bit 17: sbb ecx-width, V=0xFFFFFFFF, clc  (dst==src two-op form)
mov ecx, 0xFFFFFFFF
mov esi, 0xFFFFFFFF
clc
sbb ecx, esi
pushfq
pop r8
mov eax, 0xFFFFFFFF
clc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 17
or rbx, rax

; bit 18: sbb ecx-width, V=0x12345678, stc  (dst==src two-op form)
mov ecx, 0x12345678
mov esi, 0x12345678
stc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x12345678
stc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 18
or rbx, rax

; bit 19: sbb ecx-width, V=0x12345678, clc  (dst==src two-op form)
mov ecx, 0x12345678
mov esi, 0x12345678
clc
sbb ecx, esi
pushfq
pop r8
mov eax, 0x12345678
clc
sbb eax, eax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 19
or rbx, rax

; bit 20: adc rcx-width, V=0x7FFFFFFFFFFFFFFF, stc  (dst==src two-op form)
mov rcx, 0x7FFFFFFFFFFFFFFF
mov rsi, 0x7FFFFFFFFFFFFFFF
stc
adc rcx, rsi
pushfq
pop r8
mov rax, 0x7FFFFFFFFFFFFFFF
stc
adc rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 20
or rbx, rax

; bit 21: adc rcx-width, V=0x7FFFFFFFFFFFFFFF, clc  (dst==src two-op form)
mov rcx, 0x7FFFFFFFFFFFFFFF
mov rsi, 0x7FFFFFFFFFFFFFFF
clc
adc rcx, rsi
pushfq
pop r8
mov rax, 0x7FFFFFFFFFFFFFFF
clc
adc rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 21
or rbx, rax

; bit 22: adc rcx-width, V=0x8000000000000000, stc  (dst==src two-op form)
mov rcx, 0x8000000000000000
mov rsi, 0x8000000000000000
stc
adc rcx, rsi
pushfq
pop r8
mov rax, 0x8000000000000000
stc
adc rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 22
or rbx, rax

; bit 23: adc rcx-width, V=0x8000000000000000, clc  (dst==src two-op form)
mov rcx, 0x8000000000000000
mov rsi, 0x8000000000000000
clc
adc rcx, rsi
pushfq
pop r8
mov rax, 0x8000000000000000
clc
adc rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 23
or rbx, rax

; bit 24: adc rcx-width, V=0x123456789ABCDEF0, stc  (dst==src two-op form)
mov rcx, 0x123456789ABCDEF0
mov rsi, 0x123456789ABCDEF0
stc
adc rcx, rsi
pushfq
pop r8
mov rax, 0x123456789ABCDEF0
stc
adc rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 24
or rbx, rax

; bit 25: adc rcx-width, V=0x123456789ABCDEF0, clc  (dst==src two-op form)
mov rcx, 0x123456789ABCDEF0
mov rsi, 0x123456789ABCDEF0
clc
adc rcx, rsi
pushfq
pop r8
mov rax, 0x123456789ABCDEF0
clc
adc rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 25
or rbx, rax

; bit 26: sbb rcx-width, V=0x7FFFFFFFFFFFFFFF, stc  (dst==src two-op form)
mov rcx, 0x7FFFFFFFFFFFFFFF
mov rsi, 0x7FFFFFFFFFFFFFFF
stc
sbb rcx, rsi
pushfq
pop r8
mov rax, 0x7FFFFFFFFFFFFFFF
stc
sbb rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 26
or rbx, rax

; bit 27: sbb rcx-width, V=0x7FFFFFFFFFFFFFFF, clc  (dst==src two-op form)
mov rcx, 0x7FFFFFFFFFFFFFFF
mov rsi, 0x7FFFFFFFFFFFFFFF
clc
sbb rcx, rsi
pushfq
pop r8
mov rax, 0x7FFFFFFFFFFFFFFF
clc
sbb rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 27
or rbx, rax

; bit 28: sbb rcx-width, V=0x8000000000000000, stc  (dst==src two-op form)
mov rcx, 0x8000000000000000
mov rsi, 0x8000000000000000
stc
sbb rcx, rsi
pushfq
pop r8
mov rax, 0x8000000000000000
stc
sbb rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 28
or rbx, rax

; bit 29: sbb rcx-width, V=0x8000000000000000, clc  (dst==src two-op form)
mov rcx, 0x8000000000000000
mov rsi, 0x8000000000000000
clc
sbb rcx, rsi
pushfq
pop r8
mov rax, 0x8000000000000000
clc
sbb rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 29
or rbx, rax

; bit 30: sbb rcx-width, V=0x123456789ABCDEF0, stc  (dst==src two-op form)
mov rcx, 0x123456789ABCDEF0
mov rsi, 0x123456789ABCDEF0
stc
sbb rcx, rsi
pushfq
pop r8
mov rax, 0x123456789ABCDEF0
stc
sbb rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 30
or rbx, rax

; bit 31: sbb rcx-width, V=0x123456789ABCDEF0, clc  (dst==src two-op form)
mov rcx, 0x123456789ABCDEF0
mov rsi, 0x123456789ABCDEF0
clc
sbb rcx, rsi
pushfq
pop r8
mov rax, 0x123456789ABCDEF0
clc
sbb rax, rax
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp rcx, rax
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, 31
or rbx, rax

hlt
