#!/usr/bin/env python3
"""Generate the same-register (Dst==Src) aliasing sweep (.asm tests in this dir).

Why this exists: the Portal 2 packssdw miscompile (f82194265) and the
AdcWithFlags i32 OF bug (4232f46da) were both instances of one disease — a
multi-instruction PPC64LE lowering that writes Dst before reading a source is
wrong whenever a source aliases Dst. The conformance suite never exercised
`op reg, reg` forms, which is why both survived. These tests close that gap
mechanically.

Test shape (self-checking, no native-run expected values needed):
  reference:  dst  <- blobA, src <- blobB (identical CONTENT, distinct labels
              so load-CSE cannot merge them into one SSA value)
              op dst, src
  aliased:    alias <- blobA;  op alias, alias
  compare bitwise, set bit N of RBX on mismatch. Expected RBX == 0.
The oracle is the emulator's own non-aliased path: identical input values must
give identical results whether or not the operands share a register. Guest
dst==src maps to host aliasing through SRA affinity (guest XMM/MMX regs are
static registers and the RA prefers assigning the def straight to them), so
the hazard is exercised deterministically for the identical-source-operand
class. The RA-coalescing class (adc dst,src) additionally gets targeted
flag-checked cases mirroring the 4232f46da repro.

Regenerate with:  python3 generate_samereg.py   (writes ./*.asm)
"""

import os

OUT = os.path.dirname(os.path.abspath(__file__))

# 16-byte integer blob. Dword lanes chosen to stress saturation/packing:
# out-of-int16-range positive, INT_MIN, large negative, in-range positive.
# As bytes: mixed high bits (pshufb zeroing), mixed signs.
INT_BLOB = "dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF"
# Shift-count blob: low qword = 3 (a sane vector shift count), high qword junk.
SHIFT_BLOB = "dq 3, 0x123456789ABCDEF0"
# Float blob: +2**40 (cvttps2dq overflow -> 0x80000000 sentinel, the
# audit's probe lane), -2.5, 1.5, smallest normal.
FLT_BLOB = "dd 0x55800000, 0xC0200000, 0x3FC00000, 0x00800000"
# Double blob: +2**40, -2.5.
DBL_BLOB = "dq 0x4270000000000000, 0xC004000000000000"

HDR = """%ifdef CONFIG
{{
  "RegData": {{
      "RBX": "0x0"
  }}{features}
}}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx
"""


def features_json(features):
  if not features:
    return ""
  quoted = ", ".join(f'"{f}"' for f in features)
  return f',\n  "HostFeatures": [{quoted}]'


def xmm_section(bit, op, blob_a, blob_b, imm=None):
  i = f", {imm}" if imm is not None else ""
  return f"""
; bit {bit}: {op}{i}
movdqa xmm0, [rel {blob_a}]
movdqa xmm1, [rel {blob_b}]
{op} xmm0, xmm1{i}
movdqa xmm2, [rel {blob_a}]
{op} xmm2, xmm2{i}
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, {bit}
or rbx, rax
"""


def xmm_single_section(bit, op, blob_a, blob_b, imm=None):
  # Single-source form (op dst, src reads only src, or scalar ops that merge
  # dst upper lanes -- upper merge is still equal because ref dst == blobA).
  i = f", {imm}" if imm is not None else ""
  return f"""
; bit {bit}: {op}{i} (single-source dst==src)
movdqa xmm0, [rel {blob_a}]
movdqa xmm1, [rel {blob_b}]
{op} xmm0, xmm1{i}
movdqa xmm2, [rel {blob_a}]
{op} xmm2, xmm2{i}
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, {bit}
or rbx, rax
"""


def mmx_section(bit, op, blob_a, blob_b, imm=None):
  i = f", {imm}" if imm is not None else ""
  return f"""
; bit {bit}: {op}{i} (MMX)
movq mm0, [rel {blob_a}]
movq mm1, [rel {blob_b}]
{op} mm0, mm1{i}
movq mm2, [rel {blob_a}]
{op} mm2, mm2{i}
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, {bit}
or rbx, rax
"""


def mmx_single_section(bit, op, blob_a, blob_b, imm=None):
  i = f", {imm}" if imm is not None else ""
  return f"""
; bit {bit}: {op}{i} (MMX single-source dst==src)
movq mm0, [rel {blob_a}]
movq mm1, [rel {blob_b}]
{op} mm0, mm1{i}
movq mm2, [rel {blob_a}]
{op} mm2, mm2{i}
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, {bit}
or rbx, rax
"""


def write_file(name, sections, data, features=None):
  body = HDR.format(features=features_json(features))
  assert len(sections) <= 64, f"{name}: {len(sections)} sections exceed RBX bits"
  for bit, emit in enumerate(sections):
    body += emit(bit)
  body += "\nhlt\n\nalign 16\n"
  for label, blob in data:
    body += f"{label}:\n{blob}\n"
  with open(os.path.join(OUT, name), "w") as f:
    f.write(body)
  print(f"{name}: {len(sections)} ops")


def S(op, kind="xmm2", blob="ia", imm=None):
  # kind: xmm2 (two-src), xmm1 (single-src), mmx2, mmx1
  a, b = blob + "_a", blob + "_b"
  fn = {"xmm2": xmm_section, "xmm1": xmm_single_section,
        "mmx2": mmx_section, "mmx1": mmx_single_section}[kind]
  return lambda bit: fn(bit, op, a, b, imm)


# ---------------------------------------------------------------- MMX base
mmx_two = [
  "packsswb", "packssdw", "packuswb",
  "punpcklbw", "punpcklwd", "punpckldq",
  "punpckhbw", "punpckhwd", "punpckhdq",
  "paddb", "paddw", "paddd", "paddsb", "paddsw", "paddusb", "paddusw",
  "psubb", "psubw", "psubd", "psubsb", "psubsw", "psubusb", "psubusw",
  "pmullw", "pmulhw", "pmulhuw", "pmaddwd",
  "pand", "pandn", "por", "pxor",
  "pcmpeqb", "pcmpeqw", "pcmpeqd", "pcmpgtb", "pcmpgtw", "pcmpgtd",
  "pavgb", "pavgw", "pmaxub", "pmaxsw", "pminub", "pminsw", "psadbw",
]
mmx_shift = ["psllw", "pslld", "psllq", "psrlw", "psrld", "psrlq", "psraw", "psrad"]

sections = [S(op, "mmx2") for op in mmx_two]
sections += [S(op, "mmx2", blob="is") for op in mmx_shift]
sections += [S("pshufw", "mmx1", imm="0xB1")]
write_file("mmx_samereg.asm", sections,
           [("ia_a", INT_BLOB), ("ia_b", INT_BLOB),
            ("is_a", SHIFT_BLOB), ("is_b", SHIFT_BLOB)])

# ---------------------------------------------------------------- MMX SSSE3
sections = [S(op, "mmx2") for op in
            ["phaddw", "phaddd", "phaddsw", "phsubw", "phsubd", "phsubsw",
             "pmaddubsw", "pshufb", "psignb", "psignw", "psignd", "pmulhrsw"]]
sections += [S("palignr", "mmx2", imm="3")]
sections += [S(op, "mmx1") for op in ["pabsb", "pabsw", "pabsd"]]
write_file("mmx_ssse3_samereg.asm", sections,
           [("ia_a", INT_BLOB), ("ia_b", INT_BLOB)],
           features=["SSSE3"])

# ---------------------------------------------------------------- SSE2 int
sse2_two = mmx_two + ["punpcklqdq", "punpckhqdq", "pmuludq"]
sections = [S(op, "xmm2") for op in sse2_two]
sections += [S(op, "xmm2", blob="is") for op in mmx_shift]
sections += [S(op, "xmm1", imm="0xB1") for op in ["pshufd", "pshuflw", "pshufhw"]]
write_file("sse2_samereg_int.asm", sections,
           [("ia_a", INT_BLOB), ("ia_b", INT_BLOB),
            ("is_a", SHIFT_BLOB), ("is_b", SHIFT_BLOB)])

# ---------------------------------------------------------------- SSE float
flt_two = ["addps", "subps", "mulps", "divps", "minps", "maxps",
           "unpcklps", "unpckhps",
           "addsubps", "haddps", "hsubps",
           "addss", "subss", "mulss", "divss", "minss", "maxss"]
dbl_two = ["addpd", "subpd", "mulpd", "divpd", "minpd", "maxpd",
           "unpcklpd", "unpckhpd",
           "addsubpd", "haddpd", "hsubpd",
           "addsd", "subsd", "mulsd", "divsd", "minsd", "maxsd"]
sections = [S(op, "xmm2", blob="fa") for op in flt_two]
sections += [S(op, "xmm2", blob="da") for op in dbl_two]
sections += [S("cmpps", "xmm2", blob="fa", imm=c) for c in (0, 1, 3)]
sections += [S("cmppd", "xmm2", blob="da", imm=c) for c in (0, 1, 3)]
sections += [S("cmpss", "xmm2", blob="fa", imm=1)]
sections += [S("cmpsd", "xmm2", blob="da", imm=1)]
sections += [S("shufps", "xmm2", blob="fa", imm="0xB1")]
sections += [S("shufpd", "xmm2", blob="da", imm="1")]
write_file("sse_samereg_float.asm", sections,
           [("fa_a", FLT_BLOB), ("fa_b", FLT_BLOB),
            ("da_a", DBL_BLOB), ("da_b", DBL_BLOB)])

# ------------------------------------------------- SSE float single-source
# Includes the audit's RA probe: cvttps2dq with a +2**40 lane must produce
# the 0x80000000 sentinel, which the lowering computes by re-reading the
# FLOAT source after writing the integer Dst.
sections = [S(op, "xmm1", blob="fa") for op in
            ["sqrtps", "rcpps", "rsqrtps", "sqrtss", "rcpss", "rsqrtss",
             "cvttps2dq", "cvtps2dq", "cvtdq2ps", "cvtps2pd",
             "movshdup", "movsldup"]]
sections += [S(op, "xmm1", blob="da") for op in
             ["sqrtpd", "sqrtsd", "cvttpd2dq", "cvtpd2dq", "cvtdq2pd",
              "cvtpd2ps", "cvtss2sd", "cvtsd2ss", "movddup"]]
sections += [S(op, "xmm1", blob="ia") for op in
             ["cvtdq2ps", "cvtdq2pd"]]
write_file("sse_samereg_cvt.asm", sections,
           [("fa_a", FLT_BLOB), ("fa_b", FLT_BLOB),
            ("da_a", DBL_BLOB), ("da_b", DBL_BLOB),
            ("ia_a", INT_BLOB), ("ia_b", INT_BLOB)])

# ---------------------------------------------------------------- SSSE3 xmm
sections = [S(op, "xmm2") for op in
            ["phaddw", "phaddd", "phaddsw", "phsubw", "phsubd", "phsubsw",
             "pmaddubsw", "pshufb", "psignb", "psignw", "psignd", "pmulhrsw"]]
sections += [S("palignr", "xmm2", imm="5")]
sections += [S(op, "xmm1") for op in ["pabsb", "pabsw", "pabsd"]]
write_file("ssse3_samereg.asm", sections,
           [("ia_a", INT_BLOB), ("ia_b", INT_BLOB)],
           features=["SSSE3"])

# ---------------------------------------------------------------- SSE4.1/4.2
sections = [S(op, "xmm2") for op in
            ["packusdw", "pmulld", "pmuldq", "pcmpeqq",
             "pminsb", "pminsd", "pminuw", "pminud",
             "pmaxsb", "pmaxsd", "pmaxuw", "pmaxud"]]
sections += [S("mpsadbw", "xmm2", imm="0x2")]
sections += [S("pblendw", "xmm2", imm="0x33")]
sections += [S("blendps", "xmm2", blob="fa", imm="5")]
sections += [S("blendpd", "xmm2", blob="da", imm="1")]
sections += [S("dpps", "xmm2", blob="fa", imm="0xF1")]
sections += [S("dppd", "xmm2", blob="da", imm="0x31")]
sections += [S("insertps", "xmm2", blob="fa", imm="0x1D")]
sections += [S("roundps", "xmm1", blob="fa", imm="0")]
sections += [S("roundpd", "xmm1", blob="da", imm="1")]
sections += [S("roundss", "xmm1", blob="fa", imm="3")]
sections += [S("roundsd", "xmm1", blob="da", imm="2")]
sections += [S("phminposuw", "xmm1")]
sections += [S(op, "xmm1") for op in ["pmovsxbw", "pmovzxbd", "pmovsxdq"]]
write_file("sse41_samereg.asm", sections,
           [("ia_a", INT_BLOB), ("ia_b", INT_BLOB),
            ("fa_a", FLT_BLOB), ("fa_b", FLT_BLOB),
            ("da_a", DBL_BLOB), ("da_b", DBL_BLOB)],
           features=["SSE4.1"])

write_file("sse42_samereg.asm", [S("pcmpgtq", "xmm2")],
           [("ia_a", INT_BLOB), ("ia_b", INT_BLOB)],
           features=["SSE4.2"])

# ------------------------------------------------------------ GPR adc/sbb
# Mirrors the 4232f46da repro shape: two-op form guest dst==src, full flag
# compare (OF|SF|ZF|AF|PF|CF = 0x8D5). The host-level trigger is RA
# coalescing (needs the WithFlags path + DFCE), so unlike the vector sweep
# this is not guaranteed to alias on every RA revision -- it pins down the
# convicted i32 OF case and stands guard for the class.
ADC_HDR = HDR
adc_cases = []
for op in ("adc", "sbb"):
  for reg32, val in (("eax", "0x7FFFFFFF"), ("eax", "0x80000000"),
                     ("eax", "0x40000000"), ("eax", "0xFFFFFFFF"),
                     ("eax", "0x12345678")):
    for cf in ("stc", "clc"):
      adc_cases.append((op, "e", val, cf))
for op in ("adc", "sbb"):
  for val in ("0x7FFFFFFFFFFFFFFF", "0x8000000000000000", "0x123456789ABCDEF0"):
    for cf in ("stc", "clc"):
      adc_cases.append((op, "r", val, cf))

body = ADC_HDR.format(features="")
# Suite convention (see CALL.asm): tests that touch the stack must point RSP
# at the harness-mapped region themselves -- the default RSP is not usable
# and pushfq faults without this.
body += "mov rsp, 0xe8000000\n"
for bit, (op, width, val, cf) in enumerate(adc_cases):
  if width == "e":
    ref_d, ref_s, ali = "ecx", "esi", "eax"
    ref_d64, ali64 = "rcx", "rax"
  else:
    ref_d, ref_s, ali = "rcx", "rsi", "rax"
    ref_d64, ali64 = "rcx", "rax"
  body += f"""
; bit {bit}: {op} {ref_d}-width, V={val}, {cf}  (dst==src two-op form)
mov {ref_d}, {val}
mov {ref_s}, {val}
{cf}
{op} {ref_d}, {ref_s}
pushfq
pop r8
mov {ali}, {val}
{cf}
{op} {ali}, {ali}
pushfq
pop r9
xor r8, r9              ; flag delta
and r8, 0x8D5           ; OF|SF|ZF|AF|PF|CF
cmp {ref_d64}, {ali64}
setne al
movzx eax, al
or rax, r8
cmp rax, 0
setne al
movzx eax, al
shl rax, {bit}
or rbx, rax
"""
body += "\nhlt\n"
with open(os.path.join(OUT, "adc_sbb_samereg_flags.asm"), "w") as f:
  f.write(body)
print(f"adc_sbb_samereg_flags.asm: {len(adc_cases)} cases")
