%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  }
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: packsswb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
packsswb mm0, mm1
movq mm2, [rel ia_a]
packsswb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: packssdw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
packssdw mm0, mm1
movq mm2, [rel ia_a]
packssdw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: packuswb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
packuswb mm0, mm1
movq mm2, [rel ia_a]
packuswb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: punpcklbw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
punpcklbw mm0, mm1
movq mm2, [rel ia_a]
punpcklbw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: punpcklwd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
punpcklwd mm0, mm1
movq mm2, [rel ia_a]
punpcklwd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: punpckldq (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
punpckldq mm0, mm1
movq mm2, [rel ia_a]
punpckldq mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: punpckhbw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
punpckhbw mm0, mm1
movq mm2, [rel ia_a]
punpckhbw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: punpckhwd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
punpckhwd mm0, mm1
movq mm2, [rel ia_a]
punpckhwd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: punpckhdq (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
punpckhdq mm0, mm1
movq mm2, [rel ia_a]
punpckhdq mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: paddb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
paddb mm0, mm1
movq mm2, [rel ia_a]
paddb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: paddw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
paddw mm0, mm1
movq mm2, [rel ia_a]
paddw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: paddd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
paddd mm0, mm1
movq mm2, [rel ia_a]
paddd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: paddsb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
paddsb mm0, mm1
movq mm2, [rel ia_a]
paddsb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: paddsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
paddsw mm0, mm1
movq mm2, [rel ia_a]
paddsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: paddusb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
paddusb mm0, mm1
movq mm2, [rel ia_a]
paddusb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: paddusw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
paddusw mm0, mm1
movq mm2, [rel ia_a]
paddusw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 15
or rbx, rax

; bit 16: psubb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psubb mm0, mm1
movq mm2, [rel ia_a]
psubb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 16
or rbx, rax

; bit 17: psubw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psubw mm0, mm1
movq mm2, [rel ia_a]
psubw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 17
or rbx, rax

; bit 18: psubd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psubd mm0, mm1
movq mm2, [rel ia_a]
psubd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 18
or rbx, rax

; bit 19: psubsb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psubsb mm0, mm1
movq mm2, [rel ia_a]
psubsb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 19
or rbx, rax

; bit 20: psubsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psubsw mm0, mm1
movq mm2, [rel ia_a]
psubsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 20
or rbx, rax

; bit 21: psubusb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psubusb mm0, mm1
movq mm2, [rel ia_a]
psubusb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 21
or rbx, rax

; bit 22: psubusw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psubusw mm0, mm1
movq mm2, [rel ia_a]
psubusw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 22
or rbx, rax

; bit 23: pmullw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmullw mm0, mm1
movq mm2, [rel ia_a]
pmullw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 23
or rbx, rax

; bit 24: pmulhw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmulhw mm0, mm1
movq mm2, [rel ia_a]
pmulhw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 24
or rbx, rax

; bit 25: pmulhuw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmulhuw mm0, mm1
movq mm2, [rel ia_a]
pmulhuw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 25
or rbx, rax

; bit 26: pmaddwd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmaddwd mm0, mm1
movq mm2, [rel ia_a]
pmaddwd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 26
or rbx, rax

; bit 27: pand (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pand mm0, mm1
movq mm2, [rel ia_a]
pand mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 27
or rbx, rax

; bit 28: pandn (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pandn mm0, mm1
movq mm2, [rel ia_a]
pandn mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 28
or rbx, rax

; bit 29: por (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
por mm0, mm1
movq mm2, [rel ia_a]
por mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 29
or rbx, rax

; bit 30: pxor (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pxor mm0, mm1
movq mm2, [rel ia_a]
pxor mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 30
or rbx, rax

; bit 31: pcmpeqb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pcmpeqb mm0, mm1
movq mm2, [rel ia_a]
pcmpeqb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 31
or rbx, rax

; bit 32: pcmpeqw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pcmpeqw mm0, mm1
movq mm2, [rel ia_a]
pcmpeqw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 32
or rbx, rax

; bit 33: pcmpeqd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pcmpeqd mm0, mm1
movq mm2, [rel ia_a]
pcmpeqd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 33
or rbx, rax

; bit 34: pcmpgtb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pcmpgtb mm0, mm1
movq mm2, [rel ia_a]
pcmpgtb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 34
or rbx, rax

; bit 35: pcmpgtw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pcmpgtw mm0, mm1
movq mm2, [rel ia_a]
pcmpgtw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 35
or rbx, rax

; bit 36: pcmpgtd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pcmpgtd mm0, mm1
movq mm2, [rel ia_a]
pcmpgtd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 36
or rbx, rax

; bit 37: pavgb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pavgb mm0, mm1
movq mm2, [rel ia_a]
pavgb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 37
or rbx, rax

; bit 38: pavgw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pavgw mm0, mm1
movq mm2, [rel ia_a]
pavgw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 38
or rbx, rax

; bit 39: pmaxub (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmaxub mm0, mm1
movq mm2, [rel ia_a]
pmaxub mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 39
or rbx, rax

; bit 40: pmaxsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmaxsw mm0, mm1
movq mm2, [rel ia_a]
pmaxsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 40
or rbx, rax

; bit 41: pminub (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pminub mm0, mm1
movq mm2, [rel ia_a]
pminub mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 41
or rbx, rax

; bit 42: pminsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pminsw mm0, mm1
movq mm2, [rel ia_a]
pminsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 42
or rbx, rax

; bit 43: psadbw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psadbw mm0, mm1
movq mm2, [rel ia_a]
psadbw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 43
or rbx, rax

; bit 44: psllw (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
psllw mm0, mm1
movq mm2, [rel is_a]
psllw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 44
or rbx, rax

; bit 45: pslld (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
pslld mm0, mm1
movq mm2, [rel is_a]
pslld mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 45
or rbx, rax

; bit 46: psllq (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
psllq mm0, mm1
movq mm2, [rel is_a]
psllq mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 46
or rbx, rax

; bit 47: psrlw (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
psrlw mm0, mm1
movq mm2, [rel is_a]
psrlw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 47
or rbx, rax

; bit 48: psrld (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
psrld mm0, mm1
movq mm2, [rel is_a]
psrld mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 48
or rbx, rax

; bit 49: psrlq (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
psrlq mm0, mm1
movq mm2, [rel is_a]
psrlq mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 49
or rbx, rax

; bit 50: psraw (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
psraw mm0, mm1
movq mm2, [rel is_a]
psraw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 50
or rbx, rax

; bit 51: psrad (MMX)
movq mm0, [rel is_a]
movq mm1, [rel is_b]
psrad mm0, mm1
movq mm2, [rel is_a]
psrad mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 51
or rbx, rax

; bit 52: pshufw, 0xB1 (MMX single-source dst==src)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pshufw mm0, mm1, 0xB1
movq mm2, [rel ia_a]
pshufw mm2, mm2, 0xB1
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 52
or rbx, rax

hlt

align 16
ia_a:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
ia_b:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
is_a:
dq 3, 0x123456789ABCDEF0
is_b:
dq 3, 0x123456789ABCDEF0
