%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  },
  "HostFeatures": ["SSSE3"]
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: phaddw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
phaddw mm0, mm1
movq mm2, [rel ia_a]
phaddw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: phaddd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
phaddd mm0, mm1
movq mm2, [rel ia_a]
phaddd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: phaddsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
phaddsw mm0, mm1
movq mm2, [rel ia_a]
phaddsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: phsubw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
phsubw mm0, mm1
movq mm2, [rel ia_a]
phsubw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: phsubd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
phsubd mm0, mm1
movq mm2, [rel ia_a]
phsubd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: phsubsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
phsubsw mm0, mm1
movq mm2, [rel ia_a]
phsubsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: pmaddubsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmaddubsw mm0, mm1
movq mm2, [rel ia_a]
pmaddubsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: pshufb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pshufb mm0, mm1
movq mm2, [rel ia_a]
pshufb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: psignb (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psignb mm0, mm1
movq mm2, [rel ia_a]
psignb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: psignw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psignw mm0, mm1
movq mm2, [rel ia_a]
psignw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: psignd (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
psignd mm0, mm1
movq mm2, [rel ia_a]
psignd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: pmulhrsw (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pmulhrsw mm0, mm1
movq mm2, [rel ia_a]
pmulhrsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: palignr, 3 (MMX)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
palignr mm0, mm1, 3
movq mm2, [rel ia_a]
palignr mm2, mm2, 3
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: pabsb (MMX single-source dst==src)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pabsb mm0, mm1
movq mm2, [rel ia_a]
pabsb mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: pabsw (MMX single-source dst==src)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pabsw mm0, mm1
movq mm2, [rel ia_a]
pabsw mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: pabsd (MMX single-source dst==src)
movq mm0, [rel ia_a]
movq mm1, [rel ia_b]
pabsd mm0, mm1
movq mm2, [rel ia_a]
pabsd mm2, mm2
pcmpeqb mm0, mm2
pmovmskb eax, mm0
cmp eax, 0xFF
setne al
movzx eax, al
shl rax, 15
or rbx, rax

hlt

align 16
ia_a:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
ia_b:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
