%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  }
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: packsswb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
packsswb xmm0, xmm1
movdqa xmm2, [rel ia_a]
packsswb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: packssdw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
packssdw xmm0, xmm1
movdqa xmm2, [rel ia_a]
packssdw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: packuswb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
packuswb xmm0, xmm1
movdqa xmm2, [rel ia_a]
packuswb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: punpcklbw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpcklbw xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpcklbw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: punpcklwd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpcklwd xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpcklwd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: punpckldq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpckldq xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpckldq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: punpckhbw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpckhbw xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpckhbw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: punpckhwd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpckhwd xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpckhwd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: punpckhdq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpckhdq xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpckhdq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: paddb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
paddb xmm0, xmm1
movdqa xmm2, [rel ia_a]
paddb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: paddw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
paddw xmm0, xmm1
movdqa xmm2, [rel ia_a]
paddw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: paddd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
paddd xmm0, xmm1
movdqa xmm2, [rel ia_a]
paddd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: paddsb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
paddsb xmm0, xmm1
movdqa xmm2, [rel ia_a]
paddsb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: paddsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
paddsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
paddsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: paddusb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
paddusb xmm0, xmm1
movdqa xmm2, [rel ia_a]
paddusb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: paddusw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
paddusw xmm0, xmm1
movdqa xmm2, [rel ia_a]
paddusw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 15
or rbx, rax

; bit 16: psubb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psubb xmm0, xmm1
movdqa xmm2, [rel ia_a]
psubb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 16
or rbx, rax

; bit 17: psubw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psubw xmm0, xmm1
movdqa xmm2, [rel ia_a]
psubw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 17
or rbx, rax

; bit 18: psubd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psubd xmm0, xmm1
movdqa xmm2, [rel ia_a]
psubd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 18
or rbx, rax

; bit 19: psubsb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psubsb xmm0, xmm1
movdqa xmm2, [rel ia_a]
psubsb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 19
or rbx, rax

; bit 20: psubsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psubsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
psubsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 20
or rbx, rax

; bit 21: psubusb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psubusb xmm0, xmm1
movdqa xmm2, [rel ia_a]
psubusb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 21
or rbx, rax

; bit 22: psubusw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psubusw xmm0, xmm1
movdqa xmm2, [rel ia_a]
psubusw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 22
or rbx, rax

; bit 23: pmullw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmullw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmullw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 23
or rbx, rax

; bit 24: pmulhw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmulhw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmulhw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 24
or rbx, rax

; bit 25: pmulhuw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmulhuw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmulhuw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 25
or rbx, rax

; bit 26: pmaddwd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaddwd xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaddwd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 26
or rbx, rax

; bit 27: pand
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pand xmm0, xmm1
movdqa xmm2, [rel ia_a]
pand xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 27
or rbx, rax

; bit 28: pandn
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pandn xmm0, xmm1
movdqa xmm2, [rel ia_a]
pandn xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 28
or rbx, rax

; bit 29: por
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
por xmm0, xmm1
movdqa xmm2, [rel ia_a]
por xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 29
or rbx, rax

; bit 30: pxor
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pxor xmm0, xmm1
movdqa xmm2, [rel ia_a]
pxor xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 30
or rbx, rax

; bit 31: pcmpeqb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpeqb xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpeqb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 31
or rbx, rax

; bit 32: pcmpeqw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpeqw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpeqw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 32
or rbx, rax

; bit 33: pcmpeqd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpeqd xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpeqd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 33
or rbx, rax

; bit 34: pcmpgtb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpgtb xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpgtb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 34
or rbx, rax

; bit 35: pcmpgtw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpgtw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpgtw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 35
or rbx, rax

; bit 36: pcmpgtd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpgtd xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpgtd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 36
or rbx, rax

; bit 37: pavgb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pavgb xmm0, xmm1
movdqa xmm2, [rel ia_a]
pavgb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 37
or rbx, rax

; bit 38: pavgw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pavgw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pavgw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 38
or rbx, rax

; bit 39: pmaxub
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaxub xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaxub xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 39
or rbx, rax

; bit 40: pmaxsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaxsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaxsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 40
or rbx, rax

; bit 41: pminub
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pminub xmm0, xmm1
movdqa xmm2, [rel ia_a]
pminub xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 41
or rbx, rax

; bit 42: pminsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pminsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pminsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 42
or rbx, rax

; bit 43: psadbw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psadbw xmm0, xmm1
movdqa xmm2, [rel ia_a]
psadbw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 43
or rbx, rax

; bit 44: punpcklqdq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpcklqdq xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpcklqdq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 44
or rbx, rax

; bit 45: punpckhqdq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
punpckhqdq xmm0, xmm1
movdqa xmm2, [rel ia_a]
punpckhqdq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 45
or rbx, rax

; bit 46: pmuludq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmuludq xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmuludq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 46
or rbx, rax

; bit 47: psllw
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
psllw xmm0, xmm1
movdqa xmm2, [rel is_a]
psllw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 47
or rbx, rax

; bit 48: pslld
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
pslld xmm0, xmm1
movdqa xmm2, [rel is_a]
pslld xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 48
or rbx, rax

; bit 49: psllq
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
psllq xmm0, xmm1
movdqa xmm2, [rel is_a]
psllq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 49
or rbx, rax

; bit 50: psrlw
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
psrlw xmm0, xmm1
movdqa xmm2, [rel is_a]
psrlw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 50
or rbx, rax

; bit 51: psrld
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
psrld xmm0, xmm1
movdqa xmm2, [rel is_a]
psrld xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 51
or rbx, rax

; bit 52: psrlq
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
psrlq xmm0, xmm1
movdqa xmm2, [rel is_a]
psrlq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 52
or rbx, rax

; bit 53: psraw
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
psraw xmm0, xmm1
movdqa xmm2, [rel is_a]
psraw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 53
or rbx, rax

; bit 54: psrad
movdqa xmm0, [rel is_a]
movdqa xmm1, [rel is_b]
psrad xmm0, xmm1
movdqa xmm2, [rel is_a]
psrad xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 54
or rbx, rax

; bit 55: pshufd, 0xB1 (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pshufd xmm0, xmm1, 0xB1
movdqa xmm2, [rel ia_a]
pshufd xmm2, xmm2, 0xB1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 55
or rbx, rax

; bit 56: pshuflw, 0xB1 (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pshuflw xmm0, xmm1, 0xB1
movdqa xmm2, [rel ia_a]
pshuflw xmm2, xmm2, 0xB1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 56
or rbx, rax

; bit 57: pshufhw, 0xB1 (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pshufhw xmm0, xmm1, 0xB1
movdqa xmm2, [rel ia_a]
pshufhw xmm2, xmm2, 0xB1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 57
or rbx, rax

hlt

align 16
ia_a:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
ia_b:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
is_a:
dq 3, 0x123456789ABCDEF0
is_b:
dq 3, 0x123456789ABCDEF0
