%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  },
  "HostFeatures": ["SSE4.1"]
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: packusdw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
packusdw xmm0, xmm1
movdqa xmm2, [rel ia_a]
packusdw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: pmulld
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmulld xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmulld xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: pmuldq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmuldq xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmuldq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: pcmpeqq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpeqq xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpeqq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: pminsb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pminsb xmm0, xmm1
movdqa xmm2, [rel ia_a]
pminsb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: pminsd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pminsd xmm0, xmm1
movdqa xmm2, [rel ia_a]
pminsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: pminuw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pminuw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pminuw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: pminud
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pminud xmm0, xmm1
movdqa xmm2, [rel ia_a]
pminud xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: pmaxsb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaxsb xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaxsb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: pmaxsd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaxsd xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaxsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: pmaxuw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaxuw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaxuw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: pmaxud
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaxud xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaxud xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: mpsadbw, 0x2
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
mpsadbw xmm0, xmm1, 0x2
movdqa xmm2, [rel ia_a]
mpsadbw xmm2, xmm2, 0x2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: pblendw, 0x33
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pblendw xmm0, xmm1, 0x33
movdqa xmm2, [rel ia_a]
pblendw xmm2, xmm2, 0x33
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: blendps, 5
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
blendps xmm0, xmm1, 5
movdqa xmm2, [rel fa_a]
blendps xmm2, xmm2, 5
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: blendpd, 1
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
blendpd xmm0, xmm1, 1
movdqa xmm2, [rel da_a]
blendpd xmm2, xmm2, 1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 15
or rbx, rax

; bit 16: dpps, 0xF1
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
dpps xmm0, xmm1, 0xF1
movdqa xmm2, [rel fa_a]
dpps xmm2, xmm2, 0xF1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 16
or rbx, rax

; bit 17: dppd, 0x31
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
dppd xmm0, xmm1, 0x31
movdqa xmm2, [rel da_a]
dppd xmm2, xmm2, 0x31
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 17
or rbx, rax

; bit 18: insertps, 0x1D
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
insertps xmm0, xmm1, 0x1D
movdqa xmm2, [rel fa_a]
insertps xmm2, xmm2, 0x1D
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 18
or rbx, rax

; bit 19: roundps, 0 (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
roundps xmm0, xmm1, 0
movdqa xmm2, [rel fa_a]
roundps xmm2, xmm2, 0
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 19
or rbx, rax

; bit 20: roundpd, 1 (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
roundpd xmm0, xmm1, 1
movdqa xmm2, [rel da_a]
roundpd xmm2, xmm2, 1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 20
or rbx, rax

; bit 21: roundss, 3 (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
roundss xmm0, xmm1, 3
movdqa xmm2, [rel fa_a]
roundss xmm2, xmm2, 3
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 21
or rbx, rax

; bit 22: roundsd, 2 (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
roundsd xmm0, xmm1, 2
movdqa xmm2, [rel da_a]
roundsd xmm2, xmm2, 2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 22
or rbx, rax

; bit 23: phminposuw (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
phminposuw xmm0, xmm1
movdqa xmm2, [rel ia_a]
phminposuw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 23
or rbx, rax

; bit 24: pmovsxbw (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmovsxbw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmovsxbw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 24
or rbx, rax

; bit 25: pmovzxbd (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmovzxbd xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmovzxbd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 25
or rbx, rax

; bit 26: pmovsxdq (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmovsxdq xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmovsxdq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 26
or rbx, rax

hlt

align 16
ia_a:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
ia_b:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
fa_a:
dd 0x55800000, 0xC0200000, 0x3FC00000, 0x00800000
fa_b:
dd 0x55800000, 0xC0200000, 0x3FC00000, 0x00800000
da_a:
dq 0x4270000000000000, 0xC004000000000000
da_b:
dq 0x4270000000000000, 0xC004000000000000
