%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  },
  "HostFeatures": ["SSE4.2"]
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: pcmpgtq
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pcmpgtq xmm0, xmm1
movdqa xmm2, [rel ia_a]
pcmpgtq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

hlt

align 16
ia_a:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
ia_b:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
