%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  }
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: addps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
addps xmm0, xmm1
movdqa xmm2, [rel fa_a]
addps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: subps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
subps xmm0, xmm1
movdqa xmm2, [rel fa_a]
subps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: mulps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
mulps xmm0, xmm1
movdqa xmm2, [rel fa_a]
mulps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: divps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
divps xmm0, xmm1
movdqa xmm2, [rel fa_a]
divps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: minps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
minps xmm0, xmm1
movdqa xmm2, [rel fa_a]
minps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: maxps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
maxps xmm0, xmm1
movdqa xmm2, [rel fa_a]
maxps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: unpcklps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
unpcklps xmm0, xmm1
movdqa xmm2, [rel fa_a]
unpcklps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: unpckhps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
unpckhps xmm0, xmm1
movdqa xmm2, [rel fa_a]
unpckhps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: addsubps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
addsubps xmm0, xmm1
movdqa xmm2, [rel fa_a]
addsubps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: haddps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
haddps xmm0, xmm1
movdqa xmm2, [rel fa_a]
haddps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: hsubps
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
hsubps xmm0, xmm1
movdqa xmm2, [rel fa_a]
hsubps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: addss
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
addss xmm0, xmm1
movdqa xmm2, [rel fa_a]
addss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: subss
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
subss xmm0, xmm1
movdqa xmm2, [rel fa_a]
subss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: mulss
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
mulss xmm0, xmm1
movdqa xmm2, [rel fa_a]
mulss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: divss
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
divss xmm0, xmm1
movdqa xmm2, [rel fa_a]
divss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: minss
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
minss xmm0, xmm1
movdqa xmm2, [rel fa_a]
minss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 15
or rbx, rax

; bit 16: maxss
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
maxss xmm0, xmm1
movdqa xmm2, [rel fa_a]
maxss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 16
or rbx, rax

; bit 17: addpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
addpd xmm0, xmm1
movdqa xmm2, [rel da_a]
addpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 17
or rbx, rax

; bit 18: subpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
subpd xmm0, xmm1
movdqa xmm2, [rel da_a]
subpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 18
or rbx, rax

; bit 19: mulpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
mulpd xmm0, xmm1
movdqa xmm2, [rel da_a]
mulpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 19
or rbx, rax

; bit 20: divpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
divpd xmm0, xmm1
movdqa xmm2, [rel da_a]
divpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 20
or rbx, rax

; bit 21: minpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
minpd xmm0, xmm1
movdqa xmm2, [rel da_a]
minpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 21
or rbx, rax

; bit 22: maxpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
maxpd xmm0, xmm1
movdqa xmm2, [rel da_a]
maxpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 22
or rbx, rax

; bit 23: unpcklpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
unpcklpd xmm0, xmm1
movdqa xmm2, [rel da_a]
unpcklpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 23
or rbx, rax

; bit 24: unpckhpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
unpckhpd xmm0, xmm1
movdqa xmm2, [rel da_a]
unpckhpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 24
or rbx, rax

; bit 25: addsubpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
addsubpd xmm0, xmm1
movdqa xmm2, [rel da_a]
addsubpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 25
or rbx, rax

; bit 26: haddpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
haddpd xmm0, xmm1
movdqa xmm2, [rel da_a]
haddpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 26
or rbx, rax

; bit 27: hsubpd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
hsubpd xmm0, xmm1
movdqa xmm2, [rel da_a]
hsubpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 27
or rbx, rax

; bit 28: addsd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
addsd xmm0, xmm1
movdqa xmm2, [rel da_a]
addsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 28
or rbx, rax

; bit 29: subsd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
subsd xmm0, xmm1
movdqa xmm2, [rel da_a]
subsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 29
or rbx, rax

; bit 30: mulsd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
mulsd xmm0, xmm1
movdqa xmm2, [rel da_a]
mulsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 30
or rbx, rax

; bit 31: divsd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
divsd xmm0, xmm1
movdqa xmm2, [rel da_a]
divsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 31
or rbx, rax

; bit 32: minsd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
minsd xmm0, xmm1
movdqa xmm2, [rel da_a]
minsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 32
or rbx, rax

; bit 33: maxsd
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
maxsd xmm0, xmm1
movdqa xmm2, [rel da_a]
maxsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 33
or rbx, rax

; bit 34: cmpps, 0
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cmpps xmm0, xmm1, 0
movdqa xmm2, [rel fa_a]
cmpps xmm2, xmm2, 0
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 34
or rbx, rax

; bit 35: cmpps, 1
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cmpps xmm0, xmm1, 1
movdqa xmm2, [rel fa_a]
cmpps xmm2, xmm2, 1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 35
or rbx, rax

; bit 36: cmpps, 3
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cmpps xmm0, xmm1, 3
movdqa xmm2, [rel fa_a]
cmpps xmm2, xmm2, 3
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 36
or rbx, rax

; bit 37: cmppd, 0
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cmppd xmm0, xmm1, 0
movdqa xmm2, [rel da_a]
cmppd xmm2, xmm2, 0
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 37
or rbx, rax

; bit 38: cmppd, 1
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cmppd xmm0, xmm1, 1
movdqa xmm2, [rel da_a]
cmppd xmm2, xmm2, 1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 38
or rbx, rax

; bit 39: cmppd, 3
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cmppd xmm0, xmm1, 3
movdqa xmm2, [rel da_a]
cmppd xmm2, xmm2, 3
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 39
or rbx, rax

; bit 40: cmpss, 1
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cmpss xmm0, xmm1, 1
movdqa xmm2, [rel fa_a]
cmpss xmm2, xmm2, 1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 40
or rbx, rax

; bit 41: cmpsd, 1
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cmpsd xmm0, xmm1, 1
movdqa xmm2, [rel da_a]
cmpsd xmm2, xmm2, 1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 41
or rbx, rax

; bit 42: shufps, 0xB1
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
shufps xmm0, xmm1, 0xB1
movdqa xmm2, [rel fa_a]
shufps xmm2, xmm2, 0xB1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 42
or rbx, rax

; bit 43: shufpd, 1
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
shufpd xmm0, xmm1, 1
movdqa xmm2, [rel da_a]
shufpd xmm2, xmm2, 1
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 43
or rbx, rax

hlt

align 16
fa_a:
dd 0x55800000, 0xC0200000, 0x3FC00000, 0x00800000
fa_b:
dd 0x55800000, 0xC0200000, 0x3FC00000, 0x00800000
da_a:
dq 0x4270000000000000, 0xC004000000000000
da_b:
dq 0x4270000000000000, 0xC004000000000000
