%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  }
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: sqrtps (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
sqrtps xmm0, xmm1
movdqa xmm2, [rel fa_a]
sqrtps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: rcpps (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
rcpps xmm0, xmm1
movdqa xmm2, [rel fa_a]
rcpps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: rsqrtps (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
rsqrtps xmm0, xmm1
movdqa xmm2, [rel fa_a]
rsqrtps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: sqrtss (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
sqrtss xmm0, xmm1
movdqa xmm2, [rel fa_a]
sqrtss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: rcpss (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
rcpss xmm0, xmm1
movdqa xmm2, [rel fa_a]
rcpss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: rsqrtss (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
rsqrtss xmm0, xmm1
movdqa xmm2, [rel fa_a]
rsqrtss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: cvttps2dq (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cvttps2dq xmm0, xmm1
movdqa xmm2, [rel fa_a]
cvttps2dq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: cvtps2dq (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cvtps2dq xmm0, xmm1
movdqa xmm2, [rel fa_a]
cvtps2dq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: cvtdq2ps (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cvtdq2ps xmm0, xmm1
movdqa xmm2, [rel fa_a]
cvtdq2ps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: cvtps2pd (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
cvtps2pd xmm0, xmm1
movdqa xmm2, [rel fa_a]
cvtps2pd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: movshdup (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
movshdup xmm0, xmm1
movdqa xmm2, [rel fa_a]
movshdup xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: movsldup (single-source dst==src)
movdqa xmm0, [rel fa_a]
movdqa xmm1, [rel fa_b]
movsldup xmm0, xmm1
movdqa xmm2, [rel fa_a]
movsldup xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: sqrtpd (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
sqrtpd xmm0, xmm1
movdqa xmm2, [rel da_a]
sqrtpd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: sqrtsd (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
sqrtsd xmm0, xmm1
movdqa xmm2, [rel da_a]
sqrtsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: cvttpd2dq (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cvttpd2dq xmm0, xmm1
movdqa xmm2, [rel da_a]
cvttpd2dq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: cvtpd2dq (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cvtpd2dq xmm0, xmm1
movdqa xmm2, [rel da_a]
cvtpd2dq xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 15
or rbx, rax

; bit 16: cvtdq2pd (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cvtdq2pd xmm0, xmm1
movdqa xmm2, [rel da_a]
cvtdq2pd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 16
or rbx, rax

; bit 17: cvtpd2ps (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cvtpd2ps xmm0, xmm1
movdqa xmm2, [rel da_a]
cvtpd2ps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 17
or rbx, rax

; bit 18: cvtss2sd (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cvtss2sd xmm0, xmm1
movdqa xmm2, [rel da_a]
cvtss2sd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 18
or rbx, rax

; bit 19: cvtsd2ss (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
cvtsd2ss xmm0, xmm1
movdqa xmm2, [rel da_a]
cvtsd2ss xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 19
or rbx, rax

; bit 20: movddup (single-source dst==src)
movdqa xmm0, [rel da_a]
movdqa xmm1, [rel da_b]
movddup xmm0, xmm1
movdqa xmm2, [rel da_a]
movddup xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 20
or rbx, rax

; bit 21: cvtdq2ps (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
cvtdq2ps xmm0, xmm1
movdqa xmm2, [rel ia_a]
cvtdq2ps xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 21
or rbx, rax

; bit 22: cvtdq2pd (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
cvtdq2pd xmm0, xmm1
movdqa xmm2, [rel ia_a]
cvtdq2pd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 22
or rbx, rax

hlt

align 16
fa_a:
dd 0x55800000, 0xC0200000, 0x3FC00000, 0x00800000
fa_b:
dd 0x55800000, 0xC0200000, 0x3FC00000, 0x00800000
da_a:
dq 0x4270000000000000, 0xC004000000000000
da_b:
dq 0x4270000000000000, 0xC004000000000000
ia_a:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
ia_b:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
