%ifdef CONFIG
{
  "RegData": {
      "RBX": "0x0"
  },
  "HostFeatures": ["SSSE3"]
}
%endif

; GENERATED by generate_samereg.py -- do not hand-edit; regenerate instead.
; Same-register (Dst==Src) aliasing sweep: each numbered section computes a
; reference result with distinct registers (equal input VALUES from two
; separate data blobs so CSE cannot merge the loads) and the aliased result
; with one register, then ORs bit N into RBX on any bitwise mismatch.
; RBX must be 0. A set bit convicts the lowering named at that bit's section.

xor rbx, rbx

; bit 0: phaddw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
phaddw xmm0, xmm1
movdqa xmm2, [rel ia_a]
phaddw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 0
or rbx, rax

; bit 1: phaddd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
phaddd xmm0, xmm1
movdqa xmm2, [rel ia_a]
phaddd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 1
or rbx, rax

; bit 2: phaddsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
phaddsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
phaddsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 2
or rbx, rax

; bit 3: phsubw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
phsubw xmm0, xmm1
movdqa xmm2, [rel ia_a]
phsubw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 3
or rbx, rax

; bit 4: phsubd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
phsubd xmm0, xmm1
movdqa xmm2, [rel ia_a]
phsubd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 4
or rbx, rax

; bit 5: phsubsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
phsubsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
phsubsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 5
or rbx, rax

; bit 6: pmaddubsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmaddubsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmaddubsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 6
or rbx, rax

; bit 7: pshufb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pshufb xmm0, xmm1
movdqa xmm2, [rel ia_a]
pshufb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 7
or rbx, rax

; bit 8: psignb
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psignb xmm0, xmm1
movdqa xmm2, [rel ia_a]
psignb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 8
or rbx, rax

; bit 9: psignw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psignw xmm0, xmm1
movdqa xmm2, [rel ia_a]
psignw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 9
or rbx, rax

; bit 10: psignd
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
psignd xmm0, xmm1
movdqa xmm2, [rel ia_a]
psignd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 10
or rbx, rax

; bit 11: pmulhrsw
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pmulhrsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pmulhrsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 11
or rbx, rax

; bit 12: palignr, 5
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
palignr xmm0, xmm1, 5
movdqa xmm2, [rel ia_a]
palignr xmm2, xmm2, 5
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 12
or rbx, rax

; bit 13: pabsb (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pabsb xmm0, xmm1
movdqa xmm2, [rel ia_a]
pabsb xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 13
or rbx, rax

; bit 14: pabsw (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pabsw xmm0, xmm1
movdqa xmm2, [rel ia_a]
pabsw xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 14
or rbx, rax

; bit 15: pabsd (single-source dst==src)
movdqa xmm0, [rel ia_a]
movdqa xmm1, [rel ia_b]
pabsd xmm0, xmm1
movdqa xmm2, [rel ia_a]
pabsd xmm2, xmm2
pcmpeqb xmm0, xmm2
pmovmskb eax, xmm0
cmp eax, 0xFFFF
setne al
movzx eax, al
shl rax, 15
or rbx, rax

hlt

align 16
ia_a:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
ia_b:
dd 0x00012345, 0x80000000, 0xFFFF8000, 0x00007FFF
